services:
  logparser:
    image: 192.168.50.22:8443/logparser:0.3.1
    container_name: logparser
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS:--Xmx1G}
      SERVER_PORT: ${SERVER_PORT:-8765}
      LOGPARSER_CRYPTO_KEY: ${LOGPARSER_CRYPTO_KEY:?set LOGPARSER_CRYPTO_KEY}
      LOGPARSER_CRYPTO_SALT: ${LOGPARSER_CRYPTO_SALT:?set LOGPARSER_CRYPTO_SALT}
      LOGPARSER_KEYSTORE_PASSWORD: ${LOGPARSER_KEYSTORE_PASSWORD:?set LOGPARSER_KEYSTORE_PASSWORD}
      LOGPARSER_TRUSTSTORE_PASSWORD: ${LOGPARSER_TRUSTSTORE_PASSWORD:?set LOGPARSER_TRUSTSTORE_PASSWORD}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?set CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:?set CLICKHOUSE_PASSWORD}
    volumes:
      - logparser-data:/root/logparser/data
      - ./certs:/app/certs:ro
      - ./log:/app/log
    ports:
      - "8765:8765"
      - "9443:9443"

volumes:
  logparser-data:
